blog/urls.py
from django.urls import path

from . import views

app_name = 'blog'

urlpatterns = [
    path("", views.index, name="index"),
    path("<int:page>/", views.index, name="pagination"),
    path("create/", views.create, name="create"),
    path("<slug:slug>/update/", views.update, name="update"),
    path("<slug:slug>/delete/", views.delete, name="delete"),
    path("<slug:slug>/", views.post_detail, name="post_detail"),
    
    
   
]

dk_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path("user/", include('user.urls')),
    path("blog/", include('blog.urls')),
    path('summernote/', include('django_summernote.urls')),
]

if settings.DEBUG:
     urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

user/urls.py
from django.urls import path

from . import views

app_name = 'user'

urlpatterns = [
    path("", views.index, name="index"),
    path("login/", views.signin, name="signin"),
    path("signup/", views.signup, name="signup"),
    path("logout/", views.signout, name="signout"),
]

blog/models.py
import re
from django.db import models

from user.models import CustomUser

class Post(models.Model):
    title = models.CharField(max_length=100)
    content = models.TextField()
    create_at = models.DateTimeField(auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    slug = models.SlugField(max_length=100, unique=True)
    thumb = models.ImageField(blank=True)
    user_id = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

    def trContent(self):
        return re.sub('\s*(<[^>]+>)\s*', ' ', self.content)[:150]

user/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class CustomUser(AbstractUser):
    pass

blog/forms.py
from django.forms import ModelForm
from django_summernote.widgets import SummernoteInplaceWidget

from .models import Post

# Create the form class.
class PostForm(ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'slug', 'content', 'thumb']
        widgets = {
            'content': SummernoteInplaceWidget(),
        }

user/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm):
        model = CustomUser
        fields = ('first_name', 'last_name', 'username', 'email')
    
    def __init__(self, *args, **kwargs):
        super(CustomUserCreationForm, self).__init__(*args, **kwargs)
        self.fields['first_name'].widget.attrs['autofocus'] = 'on'


class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('first_name', 'last_name', 'username', 'email')

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from django.template.defaultfilters import slugify
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger

from . models import Post
from . forms import PostForm
from user . models import CustomUser

def index(request,page=1):
    post_list = Post.objects.order_by('-create_at').all()
    
    paginator = Paginator(post_list, 5)

    try:
        posts = paginator.page(page)
    except PageNotAnInteger:
        posts = paginator.page(1)
    except EmptyPage:

        posts = paginator.page(paginator.num_pages)
    content = {
        'post_list':posts,
        'pg_range':{
            'left': posts.number-3,
            'right':posts.number+3
        },
    }
    return render(request, 'blog/index.html', content)
    

def post_detail(request,slug):
    post = get_object_or_404(Post,slug=slug)

    try:
        prev_post = post.get_previous_by_create_at()
        prev_data = {
            'title': prev_post.title,
            'slug': prev_post.slug
        }
    except Post.DoesNotExist:
        prev_data = False

    try:
        next_post = post.get_next_by_create_at()
        next_data = {
            'title': next_post.title,
            'slug': next_post.slug
        }
    except Post.DoesNotExist:
        next_data = False

    return render(request, 'blog/post_detail.html',{
        'post':post, 
        'prev': prev_data, 
        'next': next_data
    })

@login_required
def create(request):
    post_form = PostForm(request.POST or None, request.FILES or None)
    if request.method == 'POST':
        if post_form.is_valid():
            post = post_form.save(commit=False)
            post.user_id = request.user
            post.save()
            return redirect('blog:post_detail', request.POST.get('slug'))
    return render(request, 'blog/create.html',{'form':post_form})

@login_required
def update(request,slug):
    post = get_object_or_404(Post,slug=slug)
    url_referer = (request.META.get('HTTP_REFERER'), reverse('blog:index'))[request.META.get('HTTP_REFERER') == None]
    if request.user == post.user_id:
        post_form = PostForm(request.POST or None, request.FILES or None, instance=post)
        if request.method == 'POST':
            if post_form.is_valid():
                post_form.save()
                return redirect('blog:post_detail', request.POST.get('slug'))
        content = {
            'form':post_form,
            'post':post,
            'back':url_referer
        }
    else:
        return redirect('blog:post_detail', slug)
    return render(request, 'blog/update.html',content)

@login_required
def delete(request,slug):
    post = get_object_or_404(Post,slug=slug)
    if request.user == post.user_id:
        post.delete()
    else:
        return redirect('blog:post_detail', slug)
    return redirect('blog:index')

dk_blog/views.py
from django.shortcuts import render

def index(request):
    return render(request, 'index.html')

user/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import login, logout

from .forms import CustomUserCreationForm

# Create your views here.

def index(request):
    return render(request, 'user/index.html')

def signin(request):
    if request.method == 'POST':
        form = AuthenticationForm(data=request.POST)
        if form.is_valid():
            user = form.get_user()
            login(request, user)
            if 'next' in request.POST:
                return redirect(request.POST.get('next'))
            return redirect('user:index')
    else:
        form = AuthenticationForm()
    return render(request, 'user/signin.html', {'form': form})

def signup(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('user:index')
    else:
        form = CustomUserCreationForm()
    return render(request, 'user/signup.html', {'form': form})

def signout(request):
    logout(request)
    return redirect('user:index')

blog/templates/blog/create.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}

{% block title %}
    Create New Post
{% endblock title %}

{% block content %}

{% block breadcrumbs %}
    {% clear_breadcrumbs %}
    {% breadcrumb "Home" "index" %}
    {% breadcrumb "Blog" "blog:index" %}
    {% breadcrumb "Create" "blog:create" %}
{% endblock %}
{% render_breadcrumbs %}

<form action="{% url 'blog:create' %}" method="post" enctype="multipart/form-data" data-unload>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Create">
    <a class="btn" href="{% url 'blog:index' %}">
        Back
    </a>
</form>
<br>

{% endblock content %}

blog/templates/blog/index.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block title %}
Blog List
{% endblock title %}

{% block content %}

{% block breadcrumbs %}
    {% clear_breadcrumbs %}
    {% breadcrumb "Home" "index" %}
    {% breadcrumb "Blog" "blog:index" %}
{% endblock %}
{% render_breadcrumbs %}

<div class="d-flex align-items-center">
    <h1>Blog List</h1>
    <span style="flex-grow: 1;"></span>
    {% if user.is_authenticated %}
    <a class="btn btn-secondary" href="{% url 'blog:create' %}">
        <i class="fa fa-plus"></i>
        Create New Post
    </a>
    {% endif %}
</div>
<ul class="list-group">
    {% for post in post_list %}
    <li class="list-group-item my-2 border-0">
        <div class="row align-items-center">
            <div class="col-lg-3 col-md-4 mb-3 mb-md-0">
                <a href="{% url 'blog:post_detail' post.slug %}">
                    {% if post.thumb %}
                    <img src="{{ post.thumb.url }}" class="img-thumbnail" alt="{{ post.thumb }}" width="100%">
                    {% else %}
                    <img src="{% static 'img/no-image.png' %}" class="img-thumbnail" alt="no image" width="100%">
                    {% endif %}
                </a>
            </div>
            <div class="col-lg-9 col-md-8">
                <div class="d-md-flex align-items-center">
                    <a href="{% url 'blog:post_detail' post.slug %}">
                        <h3> {{ post.title }}</h3>
                    </a>
                    {% if user.is_authenticated and user == post.user_id %}
                    <a href="{% url 'blog:update' post.slug %}" class="btn btn-sm btn-outline-warning ml-auto"
                        title="edit">
                        <i class="fa fa-pencil"></i>
                    </a>
                    <button class="btn btn-outline-danger btn-sm btnDeletePost ml-2" title="delete"
                        data-title="{{ post.title }}" data-url="{% url 'blog:delete' post.slug %}">
                        <i class="fa fa-trash"></i>
                    </button>
                    {% endif %}
                </div>
                <span>author : {{post.user_id}} | {{ post.create_at|date:"d M, Y, P" }}</span>
                <p class="text-truncate">{{ post.trContent|safe }}</p>
            </div>
        </div>
    </li>
    <br>
    {% endfor %}
</ul>
{% if post_list.has_other_pages %}
<nav aria-label="...">
    <ul class="pagination">
        <li class="page-item {% if not post_list.has_previous %} disabled {% endif %}">
            {% if post_list.has_previous %}
            <a class="page-link" href="{% url 'blog:pagination' post_list.previous_page_number %}">
                <i class="fa fa-arrow-left"></i> Previous
            </a>
            {% else %}
            <span class="page-link">
                <i class="fa fa-arrow-left"></i> Previous
            </span>
            {% endif %}
        </li>
        {% for i in post_list.paginator.page_range %}
        {% if post_list.number == i %}
        <li class="page-item active">
            <span class="page-link">
                {{ i }}<span class="sr-only">(current)</span>
            </span>
        </li>
        {{post_list.range_left}}
        {% elif i > pg_range.left and i < pg_range.right or post_list.paginator.num_pages == i or i == 1%}
        <li class="page-item">
            <a class="page-link" href="{% url 'blog:pagination' i  %}">{{ i }}</a>
        </li>
        {% elif pg_range.left > 1 and i >= pg_range.left or pg_range.right < post_list.paginator.num_pages and i <= pg_range.right%}
        <li class="page-item disabled">
            <span class="page-link">...</span>
        </li>
        {% endif %}
        {% endfor %}
        <li class="page-item {% if not post_list.has_next %} disabled {% endif %}">
            {% if post_list.has_next %}
            <a class="page-link" href="{% url 'blog:pagination' post_list.next_page_number %}">
                Next <i class="fa fa-arrow-right"></i>
            </a>
            {% else %}
            <span class="page-link">
                Next <i class="fa fa-arrow-right"></i>
            </span>
            {% endif %}
        </li>
    </ul>
</nav>
{% endif %}
{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'base_layout.html' %}
{% load static from staticfiles %}
{% load django_bootstrap_breadcrumbs %}

{% block title %}
{{post.title}}
{% endblock title %}

{% block content %}

{% block breadcrumbs %}
    {% clear_breadcrumbs %}
    {% breadcrumb "Home" "index" %}
    {% breadcrumb "Blog" "blog:index" %}
    {% breadcrumb post.title "blog:post_detail" slug=post.slug %}
{% endblock %}
{% render_breadcrumbs %}

{% if post.thumb %}
<img src="{{ post.thumb.url }}" alt="{{ post.thumb }}" width="100%">
{% else %}
<img src="{% static 'img/no-image.png' %}" class="img-thumbnail" alt="no image" width="100%">
{% endif %}
<div class="d-md-flex align-items-center mt-5">
    <h1> {{ post.title }}</h1>
    {% if user.is_authenticated and user == post.user_id %}
    <a href="{% url 'blog:update' post.slug %}" class="btn btn-sm btn-outline-warning ml-auto" title="edit">
        <i class="fa fa-pencil"></i>
    </a>
    <button class="btn btn-outline-danger btn-sm btnDeletePost ml-2" title="delete" data-title="{{ post.title }}"
        data-url="{% url 'blog:delete' post.slug %}">
        <i class="fa fa-trash"></i>
    </button>
    {% endif %}
</div>
<span>author : {{post.user_id}} | {{ post.create_at|date:"d M, Y, P" }}</span>
<p>{{post.content|safe}}</p>
<div class="d-flex align-items-center">
    {% if next %}
    <a href="{% url 'blog:post_detail' slug=next.slug %}">
        <i class="fa fa-arrow-left"></i>
    </a>
    <a href="{% url 'blog:post_detail' slug=next.slug %}" class="text-truncate ml-1 mr-4" style="width: 50%;">
        {{ next.title }}
    </a>
    {% endif %}
    <span class=""></span>
    {% if prev %}
    <a href="{% url 'blog:post_detail' slug=prev.slug %}" class="text-truncate text-right ml-auto mr-1" style="width: 50%;">
        {{ prev.title }}
    </a>
    <a href="{% url 'blog:post_detail' slug=prev.slug %}">
        <i class="fa fa-arrow-right"></i>
    </a>
    {% endif %}
</div>
{% endblock content %}

blog/templates/blog/update.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}
{% load django_bootstrap_breadcrumbs %}

{% block title %}
    Update Post
{% endblock title %}

{% block content %}

{% block breadcrumbs %}
    {% clear_breadcrumbs %}
    {% breadcrumb "Home" "index" %}
    {% breadcrumb "Blog" "blog:index" %}
    {% breadcrumb post.title "blog:post_detail" slug=post.slug %}
    {% breadcrumb "Update" "blog:update" slug=post.slug %}
{% endblock %}
{% render_breadcrumbs %}

<form action="{% url 'blog:update' post.slug %}" method="post" enctype="multipart/form-data" data-unload>
    {% csrf_token %}
    {{ form|crispy }}
    <input class="btn btn-primary" type="submit" value="Update">
    <a class="btn" href="{{ back }}">
        Back
    </a>
</form>
<br>

{% endblock content %}

templates/base_layout.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>{% block title %}Dev kids blogs{% endblock title %}</title>
    {% comment %} lib/css {% endcomment %}
    <link rel="stylesheet" href="{% static 'lib/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'lib/css/summernote-bs4.min.css' %}">
    {% comment %} lib/js {% endcomment %}
    <script src="{% static 'lib/js/promise-polyfill.min.js' %}"></script>
    <script src="{% static 'lib/js/jquery.min.js' %}"></script>
    <script src="{% static 'lib/js/popper.min.js' %}"></script>
    <script src="{% static 'lib/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'lib/js/sweetalert2.min.js' %}"></script>
    <script src="{% static 'lib/js/summernote-bs4.min.js' %}"></script>
    {% comment %} css {% endcomment %}
    <link rel="stylesheet" href="{% static 'css/main.css' %}">
</head>

<body>
    {% include 'navbar.html' %}
    <div class="container my-sm-5 py-5 bg-white">
        <div class="content px-0 px-md-5">
            {% block content %}
            <pre>Content empty</pre>
            {% endblock content %}
        </div>
    </div>
    {% comment %} js {% endcomment %}
    <script src="{% static 'js/script.js' %}"></script>
</body>

</html>

templates/index.html
{% extends 'base_layout.html' %}

{% block content %}
    <h1>Main Page</h1>
{% endblock content %}

templates/navbar.html
{% load static from staticfiles %}

<nav class="navbar navbar-expand-md navbar-light bg-light">
    
    <a class="navbar-brand" href="{% url 'index' %}">
        <img src="{% static 'img/logo.svg' %}" alt="Dev Kids" style="width: 40px; height: 40px; border-radius: 5px;">
        <strong>DEV KIDS</strong>
    </a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
            <li class="nav-item {% if request.resolver_match.namespace == '' %}active{% endif %}">
                <a class="nav-link" href="{% url 'index' %}">Home</a>
            </li>
            <li class="nav-item {% if request.resolver_match.namespace == 'blog' %}active{% endif %}">
                <a class="nav-link" href="{% url 'blog:index' %}">Blog</a>
            </li>
            {% if user.is_authenticated %}
            <li class="nav-item dropdown d-md-none">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown"
                    aria-haspopup="true" aria-expanded="false">
                    Hi,
                    <strong>
                        {% if user.first_name %}{{ user.first_name }}{% endif %}
                        {% if user.last_name %}{{ user.last_name }}{% endif %}
                        {% if not user.first_name and not user.last_name %}{{ user.username }}{% endif %}
                    </strong>
                </a>
                <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                    <a class="dropdown-item" href="{% url 'user:index' %}">
                        Open Profile
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'user:signout' %}">
                        <i class="fa fa-sign-out"></i>
                        Logout
                    </a>
                </div>
            </li>
            {% else %}
            <div class="dropdown-divider"></div>
            <li class="nav-item dropdown d-md-none">
                <a class="btn btn-primary btn-sm" href="{% url 'user:signin' %}">
                    Login
                </a>
                <a class="btn btn-secondary btn-sm" href="{% url 'user:signup' %}">
                    Signup
                </a>
            </li>
            {% endif %}
        </ul>
    </div>
    
    <div class="d-none d-md-block">
        <span style="flex-grow: 1;"></span>
        {% if user.is_authenticated %}
        <div class="dropdown">
                <a class="nav-link dropdown-toggle"  id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                    <i class="fa fa-user-circle fa-lg"></i>
                    Hi,
                    <strong>
                        {% if user.first_name %}{{ user.first_name }}{% endif %}
                        {% if user.last_name %}{{ user.last_name }}{% endif %}
                        {% if not user.first_name and not user.last_name %}{{ user.username }}{% endif %}
                    </strong>
                </a>
                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                    <a class="dropdown-item" href="{% url 'user:index' %}">
                        Open Profile
                    </a>
                    <div class="dropdown-divider"></div>
                    <a class="dropdown-item" href="{% url 'user:signout' %}">
                        <i class="fa fa-sign-out"></i>
                        Logout
                    </a>
                </div>
            </div>
        {% else %}
        <a class="btn btn-primary" href="{% url 'user:signin' %}">
            Login
        </a>
        <a class="btn btn-secondary" href="{% url 'user:signup' %}">
            Signup
        </a>
        {% endif %}
    </div>
</nav>

user/templates/user/index.html
{% extends 'base_layout.html' %}
{% load django_bootstrap_breadcrumbs %}

{% block title %}
hello from /user
{% endblock title %}

{% block content %}

{% block breadcrumbs %}
    {% clear_breadcrumbs %}
    {% breadcrumb "Home" "index" %}
    {% breadcrumb "User" "blog:user" %}
{% endblock %}
{% render_breadcrumbs %}

<h1>hello from /user</h1>
{% if user.is_authenticated %}
<pre>you have username : {{ user.username }}</pre>


<div class="d-flex align-items-center">
    {% if user.is_superuser %}
    <a class="btn btn-primary" href="{% url 'index' %}admin/">
        Open admin page
    </a>
    {% else %}
    <a class="btn btn-primary" href="{% url 'blog:index' %}">
        Open blog page
    </a>
    {% endif %}
    <span style="margin: 0 10px;">
        or
    </span>
    <a class="btn btn-secondary" href="{% url 'user:signout' %}">
        Logout
    </a>
</div>
{% else %}
<div class="d-flex align-items-center">
    <a class="btn btn-secondary" href="{% url 'user:signin' %}">
        Login
    </a>
    <span style="margin: 0 10px;">
        or
    </span>
    <a class="btn btn-secondary" href="{% url 'user:signup'%}">
        Sign up
    </a>
</div>
{% endif %}
{% endblock content %}

user/templates/user/signin.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block title %}
Login
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col col-md-6 offset-md-3">
        <h1>Login</h1>
        <form action="{% url 'user:signin' %}" method="post">
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-primary" type="submit" value="Let me in!">
        </form>
    </div>
</div>
{% endblock content %}

user/templates/user/signup.html
{% extends 'base_layout.html' %}
{% load crispy_forms_tags %}

{% block title %}
Signup
{% endblock title %}

{% block content %}
<div class="row">
    <div class="col col-md-6 offset-md-3">
        <h1>Signup</h1>
        <form action="{% url 'user:signup' %}" method="post" data-unload>
            {% csrf_token %}
            {{ form|crispy }}
            <input class="btn btn-primary" type="submit" value="Lets goo!">
        </form>
    </div>
</div>
{% endblock content %}